[package]
name = "dex"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
dex_contract = "_"

[dev-addresses]
dex_contract = "0xAA"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
